### ISSUE TITLE
No .prj ,.shx..dbf files with indian map shapefile  

### ISSUE THREAD

**Issue by shubham0508** [Princenihith/choropleth-map-using-bokeh#1]
Hii @Princenihith 

I'm a college student and doing some  R&D on data visualization I am very much interested in heatmaps .
1.I tried to this by my own  but when I try to install geopandas (Windows 10, python 3.7) rrror is thrown related to  "gdal driver path" . I could not get any way to resolve it .Have you any idea to resolve this.
2.Also there is  no additional files with indian map shapefile like .prj,.shx,.dbf etc .So , I am unable to execute this.I would be very helpful to you if u help in resolving my issue. 

Thanks in advance.

**Comment by Princenihith** [comment]
Hi @shubham0508 

1. I don't have any idea regarding the "gdal driver path"
2. I have added the .prj, .cpg, .dbf, .shx files to the repository. Hope this helps you to execute the notebook.
Thanks for looking into my repository.
